{{
    config(
        materialized='view',
        schema='marts_misa'
    )
}}

select
    h.id                              as header_id,
    h.refno                           as header_refno,
    h.year,
    h.page_index,
    h.session_id,
    h.updated_at,
    ord                               as line_index,
    (item ->> 'detail_id')                                as detail_id,
    (item ->> 'refid')                                    as refid,
    (item ->> 'inv_no')                                   as inv_no,
    (item ->> 'refdate')                                  as refdate,
    (item ->> 'reftype')                                  as reftype,
    (item ->> 'reftype_name')                             as reftype_name,
    (item ->> 'inv_date')                                 as inv_date,
    (item ->> 'posted_date')                              as posted_date,
    (item ->> 'account_number')                           as account_number,
    (item ->> 'account_name')                             as account_name,
    (item ->> 'corresponding_account_number')             as corresponding_account_number,
    (item ->> 'corresponding_account_name')               as corresponding_account_name,
    (item ->> 'account_object_code')                      as account_object_code,
    (item ->> 'account_object_name')                      as account_object_name,
    (item ->> 'branch_id')                                as branch_id,
    (item ->> 'branch_name')                              as branch_name,
    (item ->> 'currency_id')                              as currency_id,
    (item ->> 'debit_amount')::numeric                    as debit_amount,
    (item ->> 'credit_amount')::numeric                   as credit_amount,
    (item ->> 'debit_amount_oc')::numeric                 as debit_amount_oc,
    (item ->> 'credit_amount_oc')::numeric                as credit_amount_oc,
    (item ->> 'exchange_rate')::numeric                   as exchange_rate,
    (item ->> 'description')                              as description,
    (item ->> 'journal_memo')                             as journal_memo,
    (item ->> 'employee_code')                            as employee_code,
    (item ->> 'employee_name')                            as employee_name,
    (item ->> 'is_bold')::boolean                         as is_bold,
    (item ->> 'is_summary_row')::boolean                  as is_summary_row,
    (item ->> 'job_code')                                 as job_code,
    (item ->> 'job_name')                                 as job_name,
    (item ->> 'order_no')                                 as order_no,
    (item ->> 'contract_code')                            as contract_code,
    (item ->> 'list_item_code')                           as list_item_code,
    (item ->> 'list_item_name')                           as list_item_name,
    (item ->> 'budget_item_code')                         as budget_item_code,
    (item ->> 'budget_item_name')                         as budget_item_name,
    (item ->> 'expense_item_code')                        as expense_item_code,
    (item ->> 'expense_item_name')                        as expense_item_name,
    (item ->> 'project_work_code')                        as project_work_code,
    (item ->> 'project_work_name')                        as project_work_name,
    (item ->> 'pu_contract_code')                         as pu_contract_code,
    (item ->> 'organization_unit_code')                   as organization_unit_code,
    (item ->> 'organization_unit_name')                   as organization_unit_name,
    (item ->> 'loan_agreement_refno')                     as loan_agreement_refno,
    (item ->> 'lending_agreement_refno')                  as lending_agreement_refno,
    (item ->> 'un_resonable_cost')                        as un_resonable_cost,
    (item ->> 'custom_field1')                            as custom_field1,
    (item ->> 'custom_field2')                            as custom_field2,
    (item ->> 'custom_field3')                            as custom_field3,
    (item ->> 'custom_field4')                            as custom_field4,
    (item ->> 'custom_field5')                            as custom_field5,
    (item ->> 'custom_field6')                            as custom_field6,
    (item ->> 'custom_field7')                            as custom_field7,
    (item ->> 'custom_field8')                            as custom_field8,
    (item ->> 'custom_field9')                            as custom_field9,
    (item ->> 'custom_field10')                           as custom_field10,
    (item ->> 'master_custom_field1')                     as master_custom_field1,
    (item ->> 'master_custom_field2')                     as master_custom_field2,
    (item ->> 'master_custom_field3')                     as master_custom_field3,
    (item ->> 'master_custom_field4')                     as master_custom_field4,
    (item ->> 'master_custom_field5')                     as master_custom_field5,
    (item ->> 'master_custom_field6')                     as master_custom_field6,
    (item ->> 'master_custom_field7')                     as master_custom_field7,
    (item ->> 'master_custom_field8')                     as master_custom_field8,
    (item ->> 'master_custom_field9')                     as master_custom_field9,
    (item ->> 'master_custom_field10')                    as master_custom_field10
from {{ source('misa', 'journal_entries') }} h
cross join lateral jsonb_array_elements(h.data_details) with ordinality as t(item, ord)
