{{ config(
    materialized='materialized_view',
    schema='marts_salesaya'
) }}

WITH customers AS (
    SELECT * FROM {{ ref('stg_erpnext__customers') }}
)

SELECT
    customers.customer_id                                               AS name,
    customers.owner,
    customers.created_at                                                AS creation,
    customers.updated_at                                                AS modified,
    customers.modified_by,
    customers.docstatus,
    customers.idx,
    customers.naming_series,
    customers.salutation,
    customers.customer_name,
    -- customers.customer_group,
    -- customers.bizfly_customer_number,
    customers.is_internal_customer,
    customers.customer_type,
    customers.customer_rank,
    -- customers.account_manager,
    customers.lead_name,
    -- customers.opportunity_name,
    -- customers.territory,     
    -- customers.prospect_name, 
    -- customers.company_name,  
    -- customers.no_of_employees,
    -- customers.industry,      
    -- customers.market_segment,
    -- customers.tax_number,    
    -- customers.ceo_name,      
    customers.personal_document_type,
    customers.birth_date,
    customers.gender,
    customers.personal_id,
    customers.place_of_issuance,
    customers.person_name,
    customers.date_of_issuance,
    customers.first_source,
    -- customers.customer_website,
    customers.customer_journey,
    -- customers.default_currency,
    -- customers.default_bank_account,
    -- customers.default_price_list,
    -- customers.represents_company,
    -- customers.customer_pos_id,
    -- customers.website,       
    customers.language,
    -- customers.customer_details,
    customers.customer_primary_address,
    customers.primary_address,
    -- customers.image,         
    customers.customer_primary_contact,
    customers.primary_contact,
    customers.mobile_number                                             AS mobile_no,
    customers.email                                                     AS email_id,
    customers.phone_number                                              AS phone,
    customers.invoice_type,
    customers.vat_email,
    customers.vat_name,
    customers.vat_address,
    customers.personal_tax_id,
    -- customers.bank_account,  
    -- customers.payment_terms, 
    -- customers.loyalty_program,
    -- customers.loyalty_program_tier,
    customers.rank,
    customers.purchase_amount_last_12_months,
    -- customers.rank_expired_date,
    -- customers.priority_login_date,
    customers.cumulative_revenue,
    customers.cashback,
    customers.true_cumulative_revenue,
    customers.withdraw_cashback,
    customers.referrals_revenue,
    customers.pending_cashback,
    customers.priority_bank_account,
    -- customers.default_sales_partner,
    customers.default_commission_rate,
    customers.so_required,
    customers.dn_required,
    customers.is_frozen,
    customers.is_disabled                                               AS disabled,
    customers.haravan_id
    -- customers.bizfly_id,     
    -- customers.tax_id,        
    -- customers.tax_category,  
    -- customers.tax_withholding_category

FROM customers
