{{ config(
    materialized='materialized_view',
    schema='marts_salesaya'
) }}

-- Salesaya customer-lookup feed — ERPNext customers with profile, contact, identity, tax, loyalty,
-- revenue and settings attributes. Grain: 1 row per ERPNext customer.
SELECT
    erp_customer_id                     AS name,
    erp_owner                           AS owner,
    erp_created_at                      AS creation,
    erp_updated_at                      AS modified,
    erp_modified_by                     AS modified_by,
    docstatus,
    idx,
    naming_series,
    salutation,
    erp_customer_name                   AS customer_name,
    is_internal_customer,
    customer_type,
    customer_rank,
    lead_name,
    personal_document_type,
    birth_date,
    gender,
    personal_id,
    place_of_issuance,
    person_name,
    date_of_issuance,
    lead_source_id                      AS first_source,
    customer_journey,
    language,
    customer_primary_address,
    primary_address,
    customer_primary_contact,
    primary_contact,
    mobile_number                       AS mobile_no,
    email                               AS email_id,
    phone_number                        AS phone,
    invoice_type,
    vat_email,
    vat_name,
    vat_address,
    personal_tax_id,
    rank,
    purchase_amount_last_12_months,
    cumulative_revenue,
    cashback,
    true_cumulative_revenue,
    withdraw_cashback,
    referrals_revenue,
    pending_cashback,
    priority_bank_account,
    default_commission_rate,
    so_required,
    dn_required,
    is_frozen,
    is_disabled                         AS disabled,
    haravan_customer_id                 AS haravan_id
FROM {{ ref('int_crm__customers') }}
WHERE erp_customer_id IS NOT NULL
