from __future__ import annotations

from ..common import ExecutionUnitSpec, validate_execution_units


FRAPPE_ERPNEXT_NAME_SEGMENTS = ("frappe", "erpnext")


def _asset_paths(*resource_names: str) -> tuple[tuple[str, ...], ...]:
    return tuple(("ingestion", "frappe", "erpnext", resource_name) for resource_name in resource_names)


FRAPPE_ERPNEXT_EXECUTION_UNITS = validate_execution_units(
    (
        ExecutionUnitSpec(
            layer="ingestion",
            tool="dlt",
            system="frappe_erpnext",
            unit="leads",
            asset_paths=_asset_paths("leads"),
            description="Refresh ERPNext leads",
            cadence="10m",
            name_segments=FRAPPE_ERPNEXT_NAME_SEGMENTS,
            cron_schedule="1,11,21,31,41,51 * * * *",
            schedule_token="every_10m",
            schedule_description="Run ERPNext leads every 10 minutes",
            max_runtime_seconds=480,
        ),
        ExecutionUnitSpec(
            layer="ingestion",
            tool="dlt",
            system="frappe_erpnext",
            unit="sales_orders",
            asset_paths=_asset_paths("sales_orders", "sales_order_items"),
            description="Refresh ERPNext sales orders and sales order items",
            cadence="10m",
            name_segments=FRAPPE_ERPNEXT_NAME_SEGMENTS,
            cron_schedule="3,13,23,33,43,53 * * * *",
            schedule_token="every_10m",
            schedule_description="Run ERPNext sales orders and sales order items every 10 minutes",
            max_runtime_seconds=480,
        ),
        ExecutionUnitSpec(
            layer="ingestion",
            tool="dlt",
            system="frappe_erpnext",
            unit="lead_products_opportunities_batch",
            asset_paths=_asset_paths("lead_products", "opportunities"),
            description="Refresh ERPNext lead products and opportunities",
            cadence="10m",
            name_segments=FRAPPE_ERPNEXT_NAME_SEGMENTS,
            cron_schedule="5,15,25,35,45,55 * * * *",
            schedule_token="every_10m",
            schedule_description="Run ERPNext lead products and opportunities every 10 minutes",
            max_runtime_seconds=480,
        ),
        ExecutionUnitSpec(
            layer="ingestion",
            tool="dlt",
            system="frappe_erpnext",
            unit="communications_call_logs_batch",
            asset_paths=_asset_paths("communications", "call_logs"),
            description="Refresh ERPNext communications and call logs",
            cadence="10m",
            name_segments=FRAPPE_ERPNEXT_NAME_SEGMENTS,
            cron_schedule="7,17,27,37,47,57 * * * *",
            schedule_token="every_10m",
            schedule_description="Run ERPNext communications and call logs every 10 minutes",
            max_runtime_seconds=480,
        ),
        ExecutionUnitSpec(
            layer="ingestion",
            tool="dlt",
            system="frappe_erpnext",
            unit="customers",
            asset_paths=_asset_paths("customers"),
            description="Refresh ERPNext customers",
            cadence="20m",
            name_segments=FRAPPE_ERPNEXT_NAME_SEGMENTS,
            cron_schedule="2,22,42 * * * *",
            schedule_token="every_20m",
            schedule_description="Run ERPNext customers every 20 minutes",
            max_runtime_seconds=900,
        ),
        ExecutionUnitSpec(
            layer="ingestion",
            tool="dlt",
            system="frappe_erpnext",
            unit="contacts",
            asset_paths=_asset_paths("contacts"),
            description="Refresh ERPNext contacts",
            cadence="20m",
            name_segments=FRAPPE_ERPNEXT_NAME_SEGMENTS,
            cron_schedule="6,26,46 * * * *",
            schedule_token="every_20m",
            schedule_description="Run ERPNext contacts every 20 minutes",
            max_runtime_seconds=900,
        ),
        ExecutionUnitSpec(
            layer="ingestion",
            tool="dlt",
            system="frappe_erpnext",
            unit="addresses",
            asset_paths=_asset_paths("addresses"),
            description="Refresh ERPNext address records",
            cadence="20m",
            name_segments=FRAPPE_ERPNEXT_NAME_SEGMENTS,
            cron_schedule="10,30,50 * * * *",
            schedule_token="every_20m",
            schedule_description="Run ERPNext addresses records every 20 minutes",
            max_runtime_seconds=900,
        ),
        ExecutionUnitSpec(
            layer="ingestion",
            tool="dlt",
            system="frappe_erpnext",
            unit="payments_banking_buybacks_batch",
            asset_paths=_asset_paths("payment_entries", "bank_transactions", "buyback_exchanges"),
            description="Refresh ERPNext payment entries, bank transactions, and buyback exchanges",
            cadence="20m",
            name_segments=FRAPPE_ERPNEXT_NAME_SEGMENTS,
            cron_schedule="14,34,54 * * * *",
            schedule_token="every_20m",
            schedule_description="Run ERPNext payment entries, bank transactions, and buyback exchanges every 20 minutes",
            max_runtime_seconds=900,
        ),
        ExecutionUnitSpec(
            layer="ingestion",
            tool="dlt",
            system="frappe_erpnext",
            unit="documents_audit_batch",
            asset_paths=_asset_paths("comments", "files", "deleted_documents", "web_forms"),
            description="Refresh ERPNext comments, files, deleted documents, and web forms",
            cadence="20m",
            name_segments=FRAPPE_ERPNEXT_NAME_SEGMENTS,
            cron_schedule="18,38,58 * * * *",
            schedule_token="every_20m",
            schedule_description="Run ERPNext comments, files, deleted documents, and web forms every 20 minutes",
            max_runtime_seconds=900,
        ),
        ExecutionUnitSpec(
            layer="ingestion",
            tool="dlt",
            system="frappe_erpnext",
            unit="user_ops_batch",
            asset_paths=_asset_paths(
                "users",
                "view_logs",
                "access_logs",
                "user_permissions",
                "notification_settings",
                "sales_persons",
                "process_subscriptions",
            ),
            description="Refresh ERPNext users, view logs, access logs, user permissions, notification settings, sales persons, and process subscriptions",
            cadence="hourly",
            name_segments=FRAPPE_ERPNEXT_NAME_SEGMENTS,
            cron_schedule="10 * * * *",
            schedule_token="hourly",
            schedule_description="Run ERPNext users, logs, permissions, notifications, sales persons, and process subscriptions hourly at minute 10",
            max_runtime_seconds=2700,
        ),
        ExecutionUnitSpec(
            layer="ingestion",
            tool="dlt",
            system="frappe_erpnext",
            unit="master_data_batch",
            asset_paths=_asset_paths(
                "regions",
                "lead_sources",
                "sales_stages",
                "market_segments",
                "opportunity_types",
                "provinces",
                "lead_budgets",
                "lead_demands",
                "reports",
                "roles",
                "translations",
                "role_profiles",
                "bank_accounts",
                "monthly_distributions",
                "accounts",
                "todos",
                "tags",
                "product_categories",
                "serials",
                "purchase_purposes",
                "policies",
                "promotions",
                "sales_partner_types",
                "sales_teams",
                "promotion_groups",
                "uom_conversion_factors",
                "employees",
            ),
            description="Refresh ERPNext regions, lead sources, sales stages, market segments, opportunity types, provinces, lead budgets, lead demands, reports, roles, translations, role profiles, bank accounts, monthly distributions, accounts, todos, tags, product categories, serials, purchase purposes, policies, promotions, sales partner types, sales teams, promotion groups, UOM conversion factors, and employees",
            cadence="daily",
            name_segments=FRAPPE_ERPNEXT_NAME_SEGMENTS,
            cron_schedule="0 1 * * *",
            schedule_token="daily_01utc",
            schedule_description="Run ERPNext master data daily at 08:00 ICT (01:00 UTC)",
            max_runtime_seconds=3600,
        ),
        ExecutionUnitSpec(
            layer="ingestion",
            tool="dlt",
            system="frappe_erpnext",
            unit="configuration_batch",
            asset_paths=_asset_paths("property_setters"),
            description="Refresh ERPNext property setters",
            cadence="manual",
            name_segments=FRAPPE_ERPNEXT_NAME_SEGMENTS,
            max_runtime_seconds=1800,
        ),
    )
)


__all__ = ["FRAPPE_ERPNEXT_EXECUTION_UNITS"]
