FROM python:3.10-slim

ENV DAGSTER_HOME=/opt/dagster/dagster_home

RUN pip install --no-cache-dir \
    dagster \
    dagster-webserver \
    dagster-postgres \
    dagster-docker \
    "dagster-authkit[postgresql]==0.3.0"

RUN mkdir -p "$DAGSTER_HOME"

WORKDIR $DAGSTER_HOME
