from .ingestion_jobs import (
    ingestion__frappe__erpnext__address__job,
    ingestion__frappe__erpnext__activity_entities__job,
    ingestion__frappe__erpnext__contacts__job,
    ingestion__frappe__erpnext__config_entities__job,
    ingestion__frappe__erpnext__crm_activity_entities__job,
    ingestion__frappe__erpnext__crm_pipeline_entities__job,
    ingestion__frappe__erpnext__customers__job,
    ingestion__frappe__erpnext__document_entities__job,
    ingestion__frappe__erpnext__leads__job,
    ingestion__frappe__erpnext__reference_entities__job,
    ingestion__frappe__erpnext__sales_orders__job,
    ingestion__frappe__erpnext__transactional_entities__job,
    ingestion__haravan__core_entities__job,
    ingestion__haravan__inventory_locations__job,
    ingestion__haravan__reference_entities__job,
)
from .transformation_jobs import (
    transformation__marketing__marts__job,
)

all_jobs = [
    transformation__marketing__marts__job,
    ingestion__haravan__inventory_locations__job,
    ingestion__haravan__core_entities__job,
    ingestion__haravan__reference_entities__job,
    ingestion__frappe__erpnext__leads__job,
    ingestion__frappe__erpnext__sales_orders__job,
    ingestion__frappe__erpnext__crm_pipeline_entities__job,
    ingestion__frappe__erpnext__crm_activity_entities__job,
    ingestion__frappe__erpnext__customers__job,
    ingestion__frappe__erpnext__contacts__job,
    ingestion__frappe__erpnext__address__job,
    ingestion__frappe__erpnext__transactional_entities__job,
    ingestion__frappe__erpnext__document_entities__job,
    ingestion__frappe__erpnext__activity_entities__job,
    ingestion__frappe__erpnext__reference_entities__job,
    ingestion__frappe__erpnext__config_entities__job,
]

__all__ = [
    "all_jobs",
    "transformation__marketing__marts__job",
    "ingestion__haravan__inventory_locations__job",
    "ingestion__haravan__core_entities__job",
    "ingestion__haravan__reference_entities__job",
    "ingestion__frappe__erpnext__leads__job",
    "ingestion__frappe__erpnext__sales_orders__job",
    "ingestion__frappe__erpnext__crm_pipeline_entities__job",
    "ingestion__frappe__erpnext__crm_activity_entities__job",
    "ingestion__frappe__erpnext__customers__job",
    "ingestion__frappe__erpnext__contacts__job",
    "ingestion__frappe__erpnext__address__job",
    "ingestion__frappe__erpnext__transactional_entities__job",
    "ingestion__frappe__erpnext__document_entities__job",
    "ingestion__frappe__erpnext__activity_entities__job",
    "ingestion__frappe__erpnext__reference_entities__job",
    "ingestion__frappe__erpnext__config_entities__job",
]
