{{ config(
    materialized='view',
    schema='staging'
) }}

SELECT
    id::bigint AS jewelry_id,
    barcode,
    category,
    subcategory,
    supplier_code,
    supplier,
    {{ safe_cast_numeric('gold_weight') }} AS gold_weight,
    {{ safe_cast_numeric('diamond_weight') }} AS diamond_weight,
    price::numeric,
    cogs::numeric,
    quantity::int,
    order_code,
    gender,
    applique_material,
    fineness,
    material_color,
    size_type,
    {{ safe_cast_numeric('ring_size') }} AS ring_size,
    storage_size_type,
    {{ safe_cast_numeric('storage_size_1') }} AS storage_size_1,
    {{ safe_cast_numeric('storage_size_2') }} AS storage_size_2,
    design_id::bigint,
    product_name,
    product_group,
    product_type,
    sku AS old_sku,
    newsku,
    design_code,
    design_type,
    design_gender,
    design_source,
    design_year,
    {{ safe_cast_int('design_seq') }} AS design_seq,
    {{ safe_cast_int('design_variant') }} AS design_variant,
    haravan_product_type,
    vendor,
    qty_onhand::int,
    qty_commited::int,
    qty_incoming::int,
    qty_available::int,
    published_scope,
    type,
    supply_product_type,
    printing_batch,
    diamond_holder,
    code_in_title,
    ring_pair_id::bigint,
    {{ safe_cast_timestamp('database_created_at') }} AS created_at,
    {{ safe_cast_timestamp('database_updated_at') }} AS updated_at,
    _db_updated_at::timestamp,
    _dlt_load_id,
    _dlt_id

FROM {{ source('nocodb', 'jewelries') }}
