from .intermediate_catalog import INTERMEDIATE_CATALOG_EXECUTION_UNITS
from .intermediate_sales import INTERMEDIATE_SALES_EXECUTION_UNITS
from .marts_core import CORE_MARTS_EXECUTION_UNITS
from .marts_ecom import ECOM_MARTS_EXECUTION_UNITS
from .marts_finance import FINANCE_MARTS_EXECUTION_UNITS
from .marts_marketing import MARKETING_MARTS_EXECUTION_UNITS
from .marts_pancake import PANCAKE_MARTS_EXECUTION_UNITS
from .marts_sales import SALES_MARTS_EXECUTION_UNITS
from .marts_salesaya import SALESAYA_MARTS_EXECUTION_UNITS
from .marts_tech import TECH_MARTS_EXECUTION_UNITS

all_execution_units = (
    INTERMEDIATE_CATALOG_EXECUTION_UNITS
    + INTERMEDIATE_SALES_EXECUTION_UNITS
    + MARKETING_MARTS_EXECUTION_UNITS
    + SALES_MARTS_EXECUTION_UNITS
    + SALESAYA_MARTS_EXECUTION_UNITS
    + ECOM_MARTS_EXECUTION_UNITS
    + FINANCE_MARTS_EXECUTION_UNITS
    + TECH_MARTS_EXECUTION_UNITS
    + CORE_MARTS_EXECUTION_UNITS
    + PANCAKE_MARTS_EXECUTION_UNITS
)

__all__ = [
    "INTERMEDIATE_CATALOG_EXECUTION_UNITS",
    "INTERMEDIATE_SALES_EXECUTION_UNITS",
    "CORE_MARTS_EXECUTION_UNITS",
    "MARKETING_MARTS_EXECUTION_UNITS",
    "SALES_MARTS_EXECUTION_UNITS",
    "SALESAYA_MARTS_EXECUTION_UNITS",
    "ECOM_MARTS_EXECUTION_UNITS",
    "FINANCE_MARTS_EXECUTION_UNITS",
    "TECH_MARTS_EXECUTION_UNITS",
    "PANCAKE_MARTS_EXECUTION_UNITS",
    "all_execution_units",
]
